# Generated by Django 5.2.6 on 2025-09-15 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HSCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('description', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='product',
            name='country_of_origin',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='product',
            name='customs_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='uom',
            field=models.CharField(default='PCS', max_length=32),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='document_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='document_number',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='reason',
            field=models.CharField(choices=[('BONDED_RECEIPT', 'Bonded Receipt (Ex-bond)'), ('PRODUCTION_ISSUE', 'Issue to Production'), ('EXPORT_DISPATCH', 'Export Dispatch'), ('WASTAGE', 'Wastage/Destruction'), ('ADJUSTMENT', 'Adjustment')], default='ADJUSTMENT', max_length=32),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='remarks',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='BondLicense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('license_number', models.CharField(max_length=64, unique=True)),
                ('issue_date', models.DateField()),
                ('expiry_date', models.DateField()),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bond_licenses', to='inventory.warehouse')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExportDeclaration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('export_number', models.CharField(max_length=64, unique=True)),
                ('export_date', models.DateField()),
                ('destination_country', models.CharField(max_length=64)),
                ('bond_license', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='export_declarations', to='inventory.bondlicense')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='export_declaration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to='inventory.exportdeclaration'),
        ),
        migrations.AddField(
            model_name='product',
            name='hs_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='inventory.hscode'),
        ),
        migrations.CreateModel(
            name='ImportDeclaration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bill_of_entry_no', models.CharField(max_length=64, unique=True)),
                ('bill_of_entry_date', models.DateField()),
                ('uom', models.CharField(default='PCS', max_length=32)),
                ('declared_quantity', models.DecimalField(decimal_places=4, max_digits=14)),
                ('customs_value', models.DecimalField(decimal_places=2, max_digits=14)),
                ('country_of_origin', models.CharField(blank=True, max_length=64)),
                ('bond_license', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='import_declarations', to='inventory.bondlicense')),
                ('hs_code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='import_declarations', to='inventory.hscode')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='import_declarations', to='inventory.supplier')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='import_declaration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to='inventory.importdeclaration'),
        ),
        migrations.CreateModel(
            name='IOCO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('input_quantity', models.DecimalField(decimal_places=4, max_digits=12)),
                ('output_quantity', models.DecimalField(decimal_places=4, max_digits=12)),
                ('effective_date', models.DateField()),
                ('hs_code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ioco_entries', to='inventory.hscode')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ioco_entries', to='inventory.product')),
            ],
            options={
                'verbose_name': 'Input-Output Coefficient',
                'verbose_name_plural': 'Input-Output Coefficients',
            },
        ),
    ]
